### ISSUE TITLE
Update dependencies to Storybook 4 / React 16

### ISSUE THREAD

**Issue by merlinpatt** [storybooks/storybook-addon-console#3]
I just updated to the 4.0 version of Storybook and got this warning

```
@storybook/addon-console@1.0.0 requires a peer of @storybook/addon-actions@^3.0.0 but none is installed. You must install peer dependencies yourself.
```

It would be great to see the dependencies either updated or have this become a configurable option of the actions addon per #1.

**Comment by UsulPro** [comment]
Thanks for the report!

I updated dependencies, so the last version works fine with storybook v4

closing it
