### ISSUE TITLE
Use lodash-fp _curry method for more flexibility in API usage

### ISSUE THREAD

**Issue by dietergeerts** [storybooks/storybook-addon-console#4]
so we can do
```
addDecorator(withConsole());
```
instead of
```
addDecorator((storyFn, context) => withConsole()(storyFn)(context));
```

**Comment by UsulPro** [comment]
Hi, @dietergeerts! 

The way how such addons api should look was widely discussed within the main storybook repo. This implementation was chosen as it allows to combine addons of this type into one, as well as use them inside `.add` function.
(you can find similar examples of `addon-info` https://github.com/storybooks/storybook/tree/master/addons/info)

So it's kind of common way of implementing this. Maybe to make it less messy looking you can consider adding such function to your `stories.js` once:

```js
const addConsole = (storyFn, context) => withConsole()(storyFn)(context);
```
and then

```js
.addDecorator(addConsole)
```

**Comment by dietergeerts** [comment]
@UsulPro , first of all, sorry for my bad naming, What the plugins are using is real currying, but I had been confused for a while because of the lodash method _curry, which turns a function into a function that can be used either through currying, or partial application.


Second, if you would use the _curry method, `myFunction(a)(b)` would still work, with the added benefit to use it like `myFunction(a, b)`. So what I;m asking is just adding more flexibility. It also adds to readability, which is really important imho.

**Comment by UsulPro** [comment]
@dietergeerts here is an example of how we compose addons:

https://github.com/storybooks/storybook/blob/6a49aa5193309a84f7b9b92847b46fb8bc99a58b/examples/cra-kitchen-sink/src/stories/index.stories.js#L70-L80

actually I'm also not fun of how it's implemeted, but maybe better to discuss such questions in our slack https://storybooks.slack.com with other maintainers?
